### PR TITLE
Adding Mode 

### PR DESCRIPTION
**Pull request by KT360**
Mode: -Rush- in which the snake's speed increases every time food is eaten up to a certain limit

### CODE REVIEW

**Comment by phoebe-leong** [comment]
Seems like a cool concept!

**Comment by KT360** [comment]
> Seems like a cool concept!

Thanks! However, it seems like this repository isn't as active as I thought it would be :/

**Comment by phoebe-leong** [comment]
Yeah. I checked the commits, though. The last one was a month ago so theres still hope for your pull request!

**Comment by patorjk** [comment]
I've been busy, I'll try and review this this weekend. If I don't just post a comment reminding me!

**Comment by patorjk** [comment]
Nice addition, thanks for the PR!

**Comment by KT360** [comment]
> Nice addition, thanks for the PR!
Awesome!

**Pull request merged**
