### PR TITLE
Implement: Optional CSS swapping. High-score recording on localstorage. Different difficulty modes (Easy, Medium, Difficult).

### PR DESCRIPTION
**Pull request by Ultra17**

### CODE REVIEW

**Comment by Ultra17** [comment]
This is actually just about 5 commits worth of changes.

**Comment by Ultra17** [comment]
@patorjk This one is open. It's the most updated one.

**Comment by patorjk** [comment]
Sorry it's taken so long to get back to you on this. I've been really busy lately (not just saying that - I had a kid 2 weeks ago and had holidays this week). I really like these additions, my only issue is I don't like the menu at the top, I think it should be on the dialogs - the one at the start and the one that pops up when you die. However, I'll merge this in now and then do layout tweaking here in the next day or so. Thanks you for the contributions!

**Comment by Ultra17** [comment]
Haha, congrats on the baby! :p And thanks for merging, I can clean up the code if you want. I wasn't able to figure out how to change the red background when CSS is changed. That's definitely an issue.

**Comment by Yash117** [comment]
Do you mind if jQuery is used? I was thinking I could replace the old dialogs with jQuery dialog.

**Comment by Yash117** [comment]
@patorjk Are you going to leave this alone for now?

**Comment by patorjk** [comment]
I don't mind if jQuery is used. I've haven't used their dialogs, but would be fine with something if it was lightweight. Sorry for the delayed response.

**Comment by Yash117** [comment]
Hey, sorry I haven't done anything with this yet. I don't know when I will either... Anyway, since the source of the game that's up right now doesn't match the repo, feel free to revert until I PR again. (That is, if you still want this.)

**Pull request merged**
