### PR TITLE
Fix Highscore bug

### PR DESCRIPTION
**Pull request by mamamia5x**
When the game starts, it'll show your highscore of 0, not undefined.

### CODE REVIEW

**Comment by mamamia5x** [comment]
image
Because Bottom right corner says undefined

**Comment by mamamia5x** [comment]
@patorjk could you review this?

**Comment by patorjk** [comment]
This is a good catch, however, this update could cause the page to refresh infinitely if the browser doesn't accept the value. It'd probably be better to change line 684 to this:

            elmHighscorePanel.innerHTML = "Highscore: " + (localStorage.jsSnakeHighScore || 0);

**Comment by mamamia5x** [comment]
@patorjk I updated snake to the latest version, then opened pull request #77. This one has no conflicts.

**Pull request closed without merging**
