### PR TITLE
Add optional theme swapping.

### PR DESCRIPTION
**Pull request by Ultra17**

### CODE REVIEW

**Comment by Ultra17** [comment]
Some stuff still needs to be edited to change the snake block to match changed themes. Same for the red header.

**Comment by patorjk** [comment]
This sounded interesting, any reason why you closed it?

**Comment by Ultra17** [comment]
That's odd, I never did. I'll reopen it

**Comment by Ultra17** [comment]
There's a different one currently open.

**Comment by Ultra17** [comment]
@patorjk ^

**Pull request closed without merging**
