### PR TITLE
legoman8304's CSS update 

### PR DESCRIPTION
**Pull request by legoman8304**
I was playing your game and found the GitHub page, so I figured I'd make little improvements for something to do. Do what you will with it, it was just something to occupy my time!

### CODE REVIEW

**Comment by patorjk** [comment]
Thanks for the pull request! Sadly my hard drive has recently started experiencing data corruption, so it'll be a while before I can take a look (currently going through my backups). Thank you for submitting this though, when I get a chance I'll try it out!

**Comment by legoman8304** [comment]
Hey, @patorjk is your hard drive fixed? I don't mean to be pushy, but I worked decently hard on this and I'd like to know what you think. Thank you for your time!

**Comment by patorjk** [comment]
I've got an external drive with out a years worth of stuff that I'm still going through. It'll probably be months before I'm done. However, I realize that would be a bit long to wait so I went ahead and checked it out. I like the colors, some of the CSS is off, though it may be the repo, it's been a while since I've looked at it. I'll merge this in and then do some layout adjustments.

**Comment by patorjk** [comment]
As a follow up, I've deployed the version of this game in this repo to the live version on my website: http://patorjk.com/games/snake/

**Pull request merged**
